scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: server
    scrape_interval: 5s
    static_configs:
    - targets: ['aspnet-server:5131']
